export const metadata = {
  title: 'Next.js-15',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightgray",
            color: "black",
            padding: "5px",
          }}>
          <p>My Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "lightblue",
            color: "black",
            padding: "5px",
          }}>
          <p>My Footer</p>
        </footer>
      </body>
    </html>
  );
}
